# Generated by Django 4.1.7 on 2023-04-11 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_add_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='add_blog',
        ),
    ]
