# Generated by Django 4.1.7 on 2023-04-11 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_add_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(max_length=150)),
                ('name', models.TextField(max_length=100)),
                ('image', models.FileField(default='health.jpeg', upload_to='blog_photo')),
                ('categories', models.CharField(choices=[('food', 'food'), ('water', 'water'), ('vegitables', 'vegitables')], max_length=150)),
                ('time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
